window.COURSE_FILES = [
  {
    "id": "1-37",
    "year": 1,
    "course": "电路基础",
    "name": "2024final.pdf",
    "path": "grade_1/电路基础/2024final.pdf",
    "folder": "课程根目录",
    "bytes": 1780482,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "考试与练习",
    "downloadPath": "downloads/1-37.pdf"
  },
  {
    "id": "1-67",
    "year": 1,
    "course": "电路基础",
    "name": "电路基础（原书第6版） (Charles K. Alexander, Matthew N. O. Sadiku) (z-library.sk, 1lib.sk, z-lib.sk).pdf",
    "path": "grade_1/电路基础/电路基础（原书第6版） (Charles K. Alexander, Matthew N. O. Sadiku) (z-library.sk, 1lib.sk, z-lib.sk).pdf",
    "folder": "课程根目录",
    "bytes": 266166256,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "教材与参考书",
    "downloadPath": null
  },
  {
    "id": "1-66",
    "year": 1,
    "course": "电路基础",
    "name": "数字设计和计算机体系结构 (RISC-V版) Digital Design and Computer Architecture (RISC-V edition) ([美]Sarah L.Harris, David Harris) (z-library.sk, 1lib.sk, z-lib.sk).pdf",
    "path": "grade_1/电路基础/数字设计和计算机体系结构 (RISC-V版) Digital Design and Computer Architecture (RISC-V edition) ([美]Sarah L.Harris, David Harris) (z-library.sk, 1lib.sk, z-lib.sk).pdf",
    "folder": "课程根目录",
    "bytes": 231799389,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "教材与参考书",
    "downloadPath": null
  },
  {
    "id": "1-57",
    "year": 1,
    "course": "电路基础",
    "name": "Circuit_Lec13-15_Summary.pdf",
    "path": "grade_1/电路基础/复习文件/Circuit_Lec13-15_Summary.pdf",
    "folder": "复习文件",
    "bytes": 211887,
    "extension": "PDF",
    "kind": "note",
    "subfolder": "复习与总结",
    "downloadPath": "downloads/1-57.pdf"
  },
  {
    "id": "1-40",
    "year": 1,
    "course": "电路基础",
    "name": "cul.py.py",
    "path": "grade_1/电路基础/cul.py.py",
    "folder": "课程根目录",
    "bytes": 2994,
    "extension": "PY",
    "kind": "resource",
    "subfolder": "代码与附件",
    "downloadPath": "downloads/1-40.py"
  },
  {
    "id": "1-38",
    "year": 1,
    "course": "电路基础",
    "name": "Discussion 11.pdf",
    "path": "grade_1/电路基础/Discussion 11.pdf",
    "folder": "课程根目录",
    "bytes": 2061296,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "作业与报告",
    "downloadPath": "downloads/1-38.pdf"
  },
  {
    "id": "1-39",
    "year": 1,
    "course": "电路基础",
    "name": "Discussion2.pdf",
    "path": "grade_1/电路基础/Discussion2.pdf",
    "folder": "课程根目录",
    "bytes": 2051302,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "作业与报告",
    "downloadPath": "downloads/1-39.pdf"
  },
  {
    "id": "1-41",
    "year": 1,
    "course": "电路基础",
    "name": "Lec1-introduction &-Circuit Terminology.pdf",
    "path": "grade_1/电路基础/slides/Lec1-introduction &-Circuit Terminology.pdf",
    "folder": "slides",
    "bytes": 999606,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "课程课件",
    "downloadPath": "downloads/1-41.pdf"
  },
  {
    "id": "1-58",
    "year": 1,
    "course": "电路基础",
    "name": "Lec10_AC_Power_复习笔记.pdf",
    "path": "grade_1/电路基础/复习文件/Lec10_AC_Power_复习笔记.pdf",
    "folder": "复习文件",
    "bytes": 142679,
    "extension": "PDF",
    "kind": "note",
    "subfolder": "复习与总结",
    "downloadPath": "downloads/1-58.pdf"
  },
  {
    "id": "1-42",
    "year": 1,
    "course": "电路基础",
    "name": "Lec10-AC-Power calculation.pdf",
    "path": "grade_1/电路基础/slides/Lec10-AC-Power calculation.pdf",
    "folder": "slides",
    "bytes": 985746,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "课程课件",
    "downloadPath": "downloads/1-42.pdf"
  },
  {
    "id": "1-59",
    "year": 1,
    "course": "电路基础",
    "name": "Lec11_Mutual_Inductance_Transformer_复习笔记.pdf",
    "path": "grade_1/电路基础/复习文件/Lec11_Mutual_Inductance_Transformer_复习笔记.pdf",
    "folder": "复习文件",
    "bytes": 90521,
    "extension": "PDF",
    "kind": "note",
    "subfolder": "复习与总结",
    "downloadPath": "downloads/1-59.pdf"
  },
  {
    "id": "1-43",
    "year": 1,
    "course": "电路基础",
    "name": "Lec11-Mutual Inductance-Transformer [自动保存的].pdf",
    "path": "grade_1/电路基础/slides/Lec11-Mutual Inductance-Transformer [自动保存的].pdf",
    "folder": "slides",
    "bytes": 669512,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "课程课件",
    "downloadPath": "downloads/1-43.pdf"
  },
  {
    "id": "1-60",
    "year": 1,
    "course": "电路基础",
    "name": "Lec12_Three_Phase_复习笔记.pdf",
    "path": "grade_1/电路基础/复习文件/Lec12_Three_Phase_复习笔记.pdf",
    "folder": "复习文件",
    "bytes": 82655,
    "extension": "PDF",
    "kind": "note",
    "subfolder": "复习与总结",
    "downloadPath": "downloads/1-60.pdf"
  },
  {
    "id": "1-44",
    "year": 1,
    "course": "电路基础",
    "name": "Lec12-ThreePhase.pdf",
    "path": "grade_1/电路基础/slides/Lec12-ThreePhase.pdf",
    "folder": "slides",
    "bytes": 1266606,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "课程课件",
    "downloadPath": "downloads/1-44.pdf"
  },
  {
    "id": "1-62",
    "year": 1,
    "course": "电路基础",
    "name": "Lec13_Frequency_Response_复习笔记.pdf",
    "path": "grade_1/电路基础/复习文件/Lec13_Frequency_Response_复习笔记.pdf",
    "folder": "复习文件",
    "bytes": 101129,
    "extension": "PDF",
    "kind": "note",
    "subfolder": "复习与总结",
    "downloadPath": "downloads/1-62.pdf"
  },
  {
    "id": "1-61",
    "year": 1,
    "course": "电路基础",
    "name": "Lec13-14_公式与适用条件.pdf",
    "path": "grade_1/电路基础/复习文件/Lec13-14_公式与适用条件.pdf",
    "folder": "复习文件",
    "bytes": 186108,
    "extension": "PDF",
    "kind": "note",
    "subfolder": "复习与总结",
    "downloadPath": "downloads/1-61.pdf"
  },
  {
    "id": "1-45",
    "year": 1,
    "course": "电路基础",
    "name": "Lec13-Frequency_response.pdf",
    "path": "grade_1/电路基础/slides/Lec13-Frequency_response.pdf",
    "folder": "slides",
    "bytes": 1636689,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "课程课件",
    "downloadPath": "downloads/1-45.pdf"
  },
  {
    "id": "1-63",
    "year": 1,
    "course": "电路基础",
    "name": "Lec14_Filters_复习笔记.pdf",
    "path": "grade_1/电路基础/复习文件/Lec14_Filters_复习笔记.pdf",
    "folder": "复习文件",
    "bytes": 109691,
    "extension": "PDF",
    "kind": "note",
    "subfolder": "复习与总结",
    "downloadPath": "downloads/1-63.pdf"
  },
  {
    "id": "1-46",
    "year": 1,
    "course": "电路基础",
    "name": "Lec14-Filters.pdf",
    "path": "grade_1/电路基础/slides/Lec14-Filters.pdf",
    "folder": "slides",
    "bytes": 940545,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "课程课件",
    "downloadPath": "downloads/1-46.pdf"
  },
  {
    "id": "1-47",
    "year": 1,
    "course": "电路基础",
    "name": "Lec15-L Transform.pdf",
    "path": "grade_1/电路基础/slides/Lec15-L Transform.pdf",
    "folder": "slides",
    "bytes": 980709,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "课程课件",
    "downloadPath": "downloads/1-47.pdf"
  },
  {
    "id": "1-48",
    "year": 1,
    "course": "电路基础",
    "name": "Lec16-L Circuit analysis.pdf",
    "path": "grade_1/电路基础/slides/Lec16-L Circuit analysis.pdf",
    "folder": "slides",
    "bytes": 718579,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "课程课件",
    "downloadPath": "downloads/1-48.pdf"
  },
  {
    "id": "1-49",
    "year": 1,
    "course": "电路基础",
    "name": "Lec2-Kirchhoff and Node mesh analysis.pdf",
    "path": "grade_1/电路基础/slides/Lec2-Kirchhoff and Node mesh analysis.pdf",
    "folder": "slides",
    "bytes": 905839,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "课程课件",
    "downloadPath": "downloads/1-49.pdf"
  },
  {
    "id": "1-50",
    "year": 1,
    "course": "电路基础",
    "name": "Lec3-Circuit Theorem.pdf",
    "path": "grade_1/电路基础/slides/Lec3-Circuit Theorem.pdf",
    "folder": "slides",
    "bytes": 1128910,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "课程课件",
    "downloadPath": "downloads/1-50.pdf"
  },
  {
    "id": "1-51",
    "year": 1,
    "course": "电路基础",
    "name": "Lec4-Operational Amplifiers.pdf",
    "path": "grade_1/电路基础/slides/Lec4-Operational Amplifiers.pdf",
    "folder": "slides",
    "bytes": 1496596,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "课程课件",
    "downloadPath": "downloads/1-51.pdf"
  },
  {
    "id": "1-52",
    "year": 1,
    "course": "电路基础",
    "name": "Lec5-C and L.pdf",
    "path": "grade_1/电路基础/slides/Lec5-C and L.pdf",
    "folder": "slides",
    "bytes": 827458,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "课程课件",
    "downloadPath": "downloads/1-52.pdf"
  },
  {
    "id": "1-53",
    "year": 1,
    "course": "电路基础",
    "name": "Lec6-1st-Order circuit.pdf",
    "path": "grade_1/电路基础/slides/Lec6-1st-Order circuit.pdf",
    "folder": "slides",
    "bytes": 1245618,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "课程课件",
    "downloadPath": "downloads/1-53.pdf"
  },
  {
    "id": "1-56",
    "year": 1,
    "course": "电路基础",
    "name": "lec7-2nd-circuits.pdf",
    "path": "grade_1/电路基础/slides/lec7-2nd-circuits.pdf",
    "folder": "slides",
    "bytes": 1094396,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "课程课件",
    "downloadPath": "downloads/1-56.pdf"
  },
  {
    "id": "1-64",
    "year": 1,
    "course": "电路基础",
    "name": "Lec8_Phasor_复习笔记.pdf",
    "path": "grade_1/电路基础/复习文件/Lec8_Phasor_复习笔记.pdf",
    "folder": "复习文件",
    "bytes": 98741,
    "extension": "PDF",
    "kind": "note",
    "subfolder": "复习与总结",
    "downloadPath": "downloads/1-64.pdf"
  },
  {
    "id": "1-54",
    "year": 1,
    "course": "电路基础",
    "name": "Lec8-Phasor.pdf",
    "path": "grade_1/电路基础/slides/Lec8-Phasor.pdf",
    "folder": "slides",
    "bytes": 1174395,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "课程课件",
    "downloadPath": "downloads/1-54.pdf"
  },
  {
    "id": "1-65",
    "year": 1,
    "course": "电路基础",
    "name": "Lec9_AC_Steady_State_复习笔记.pdf",
    "path": "grade_1/电路基础/复习文件/Lec9_AC_Steady_State_复习笔记.pdf",
    "folder": "复习文件",
    "bytes": 105329,
    "extension": "PDF",
    "kind": "note",
    "subfolder": "复习与总结",
    "downloadPath": "downloads/1-65.pdf"
  },
  {
    "id": "1-55",
    "year": 1,
    "course": "电路基础",
    "name": "Lec9-AC-Steady State Analysis.pdf",
    "path": "grade_1/电路基础/slides/Lec9-AC-Steady State Analysis.pdf",
    "folder": "slides",
    "bytes": 1625258,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "课程课件",
    "downloadPath": "downloads/1-55.pdf"
  },
  {
    "id": "1-68",
    "year": 1,
    "course": "电路基础实验",
    "name": "01-Lab2 Guide_Spring2026.pdf",
    "path": "grade_1/电路基础实验/01-Lab2 Guide_Spring2026.pdf",
    "folder": "课程根目录",
    "bytes": 301024,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "实验指导",
    "downloadPath": "downloads/1-68.pdf"
  },
  {
    "id": "1-69",
    "year": 1,
    "course": "电路基础实验",
    "name": "01-Lab7 Guide_Spring2026.pdf",
    "path": "grade_1/电路基础实验/01-Lab7 Guide_Spring2026.pdf",
    "folder": "课程根目录",
    "bytes": 244473,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "实验指导",
    "downloadPath": "downloads/1-69.pdf"
  },
  {
    "id": "1-70",
    "year": 1,
    "course": "电路基础实验",
    "name": "02-PreLab1_Spring2026.pdf",
    "path": "grade_1/电路基础实验/02-PreLab1_Spring2026.pdf",
    "folder": "课程根目录",
    "bytes": 263629,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "实验预习",
    "downloadPath": "downloads/1-70.pdf"
  },
  {
    "id": "1-71",
    "year": 1,
    "course": "电路基础实验",
    "name": "02-PreLab2_Spring2026.pdf",
    "path": "grade_1/电路基础实验/02-PreLab2_Spring2026.pdf",
    "folder": "课程根目录",
    "bytes": 309391,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "实验预习",
    "downloadPath": "downloads/1-71.pdf"
  },
  {
    "id": "1-72",
    "year": 1,
    "course": "电路基础实验",
    "name": "02-PreLab7_Srping2026.pdf",
    "path": "grade_1/电路基础实验/02-PreLab7_Srping2026.pdf",
    "folder": "课程根目录",
    "bytes": 161370,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "实验预习",
    "downloadPath": "downloads/1-72.pdf"
  },
  {
    "id": "1-74",
    "year": 1,
    "course": "电路基础实验",
    "name": "03_Lab1_Spring2026.pdf",
    "path": "grade_1/电路基础实验/03_Lab1_Spring2026.pdf",
    "folder": "课程根目录",
    "bytes": 286027,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "实验资料",
    "downloadPath": "downloads/1-74.pdf"
  },
  {
    "id": "1-73",
    "year": 1,
    "course": "电路基础实验",
    "name": "03-Lab7 _Spring2026.pdf",
    "path": "grade_1/电路基础实验/03-Lab7 _Spring2026.pdf",
    "folder": "课程根目录",
    "bytes": 188920,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "实验资料",
    "downloadPath": "downloads/1-73.pdf"
  },
  {
    "id": "1-75",
    "year": 1,
    "course": "电路基础实验",
    "name": "Lab0 _2026Spring.pdf",
    "path": "grade_1/电路基础实验/Lab0 _2026Spring.pdf",
    "folder": "课程根目录",
    "bytes": 186878,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "实验指导",
    "downloadPath": "downloads/1-75.pdf"
  },
  {
    "id": "1-76",
    "year": 1,
    "course": "电路基础实验",
    "name": "PDF_PreLab1Report.pdf",
    "path": "grade_1/电路基础实验/PDF_PreLab1Report.pdf",
    "folder": "课程根目录",
    "bytes": 3528292,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "预习报告",
    "downloadPath": "downloads/1-76.pdf"
  },
  {
    "id": "1-78",
    "year": 1,
    "course": "电路基础实验",
    "name": "PreLab1 Report_副本.pdf",
    "path": "grade_1/电路基础实验/PreLab1 Report_副本.pdf",
    "folder": "课程根目录",
    "bytes": 3918133,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "预习报告",
    "downloadPath": "downloads/1-78.pdf"
  },
  {
    "id": "1-77",
    "year": 1,
    "course": "电路基础实验",
    "name": "PreLab1 Report.pdf",
    "path": "grade_1/电路基础实验/PreLab1 Report.pdf",
    "folder": "课程根目录",
    "bytes": 3652756,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "预习报告",
    "downloadPath": "downloads/1-77.pdf"
  },
  {
    "id": "1-98",
    "year": 1,
    "course": "高等数学",
    "name": "22-23-2-中.pdf",
    "path": "grade_1/高等数学/22-23-2-中.pdf",
    "folder": "课程根目录",
    "bytes": 1896269,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "考试与练习",
    "downloadPath": "downloads/1-98.pdf"
  },
  {
    "id": "1-99",
    "year": 1,
    "course": "高等数学",
    "name": "23-24-2-中.pdf",
    "path": "grade_1/高等数学/23-24-2-中.pdf",
    "folder": "课程根目录",
    "bytes": 2073007,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "考试与练习",
    "downloadPath": "downloads/1-99.pdf"
  },
  {
    "id": "1-100",
    "year": 1,
    "course": "高等数学",
    "name": "24-25-2-中.pdf",
    "path": "grade_1/高等数学/24-25-2-中.pdf",
    "folder": "课程根目录",
    "bytes": 183184,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "考试与练习",
    "downloadPath": "downloads/1-100.pdf"
  },
  {
    "id": "1-103",
    "year": 1,
    "course": "高等数学",
    "name": "大学数学微积分 下 第2版 (本书编委会, 上海交通大学数学科学院微积分课题组编, 上海交通大学) (z-library.sk, 1lib.sk, z-lib.sk) (1).pdf",
    "path": "grade_1/高等数学/大学数学微积分 下 第2版 (本书编委会, 上海交通大学数学科学院微积分课题组编, 上海交通大学) (z-library.sk, 1lib.sk, z-lib.sk) (1).pdf",
    "folder": "课程根目录",
    "bytes": 30004633,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "教材与参考书",
    "downloadPath": null
  },
  {
    "id": "1-110",
    "year": 1,
    "course": "高等数学",
    "name": "第八章多元函数微分学(1).pdf",
    "path": "grade_1/高等数学/第八章多元函数微分学(1).pdf",
    "folder": "课程根目录",
    "bytes": 2426345,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "课程课件",
    "downloadPath": "downloads/1-110.pdf"
  },
  {
    "id": "1-111",
    "year": 1,
    "course": "高等数学",
    "name": "第八章多元函数微分学(3).pdf",
    "path": "grade_1/高等数学/第八章多元函数微分学(3).pdf",
    "folder": "课程根目录",
    "bytes": 2916055,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "课程课件",
    "downloadPath": "downloads/1-111.pdf"
  },
  {
    "id": "1-112",
    "year": 1,
    "course": "高等数学",
    "name": "第八章多元函数微分学(4).pdf",
    "path": "grade_1/高等数学/第八章多元函数微分学(4).pdf",
    "folder": "课程根目录",
    "bytes": 8250398,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "课程课件",
    "downloadPath": "downloads/1-112.pdf"
  },
  {
    "id": "1-109",
    "year": 1,
    "course": "高等数学",
    "name": "第九章重积分(1).pdf",
    "path": "grade_1/高等数学/第九章重积分(1).pdf",
    "folder": "课程根目录",
    "bytes": 2261438,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "课程课件",
    "downloadPath": "downloads/1-109.pdf"
  },
  {
    "id": "1-108",
    "year": 1,
    "course": "高等数学",
    "name": "第七章解析几何.pdf",
    "path": "grade_1/高等数学/第七章解析几何.pdf",
    "folder": "课程根目录",
    "bytes": 2903142,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "课程课件",
    "downloadPath": "downloads/1-108.pdf"
  },
  {
    "id": "1-113",
    "year": 1,
    "course": "高等数学",
    "name": "第十一章级数(1).pdf",
    "path": "grade_1/高等数学/第十一章级数(1).pdf",
    "folder": "课程根目录",
    "bytes": 1450754,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "课程课件",
    "downloadPath": "downloads/1-113.pdf"
  },
  {
    "id": "1-114",
    "year": 1,
    "course": "高等数学",
    "name": "第十章曲线曲面积分(2).pdf",
    "path": "grade_1/高等数学/第十章曲线曲面积分(2).pdf",
    "folder": "课程根目录",
    "bytes": 5194468,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "课程课件",
    "downloadPath": "downloads/1-114.pdf"
  },
  {
    "id": "1-115",
    "year": 1,
    "course": "高等数学",
    "name": "高数1.pdf",
    "path": "grade_1/高等数学/高数1.pdf",
    "folder": "课程根目录",
    "bytes": 2828021,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "课程课件",
    "downloadPath": "downloads/1-115.pdf"
  },
  {
    "id": "1-116",
    "year": 1,
    "course": "高等数学",
    "name": "高数作业2.pdf",
    "path": "grade_1/高等数学/高数作业2.pdf",
    "folder": "课程根目录",
    "bytes": 5154110,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "作业与报告",
    "downloadPath": "downloads/1-116.pdf"
  },
  {
    "id": "1-107",
    "year": 1,
    "course": "高等数学",
    "name": "模拟练习卷二(1).pdf",
    "path": "grade_1/高等数学/模拟练习卷二(1).pdf",
    "folder": "课程根目录",
    "bytes": 1094702,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "考试与练习",
    "downloadPath": "downloads/1-107.pdf"
  },
  {
    "id": "1-106",
    "year": 1,
    "course": "高等数学",
    "name": "模拟练习卷一(1).pdf",
    "path": "grade_1/高等数学/模拟练习卷一(1).pdf",
    "folder": "课程根目录",
    "bytes": 978580,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "考试与练习",
    "downloadPath": "downloads/1-106.pdf"
  },
  {
    "id": "1-105",
    "year": 1,
    "course": "高等数学",
    "name": "期末复习.pdf",
    "path": "grade_1/高等数学/期末复习.pdf",
    "folder": "课程根目录",
    "bytes": 205085,
    "extension": "PDF",
    "kind": "note",
    "subfolder": "复习与总结",
    "downloadPath": "downloads/1-105.pdf"
  },
  {
    "id": "1-104",
    "year": 1,
    "course": "高等数学",
    "name": "微分方程coursenotes.pdf",
    "path": "grade_1/高等数学/微分方程coursenotes.pdf",
    "folder": "课程根目录",
    "bytes": 1579219,
    "extension": "PDF",
    "kind": "note",
    "subfolder": "课程笔记",
    "downloadPath": "downloads/1-104.pdf"
  },
  {
    "id": "1-102",
    "year": 1,
    "course": "高等数学",
    "name": "作业5.pdf",
    "path": "grade_1/高等数学/作业5.pdf",
    "folder": "课程根目录",
    "bytes": 1609747,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "作业与报告",
    "downloadPath": "downloads/1-102.pdf"
  },
  {
    "id": "1-101",
    "year": 1,
    "course": "高等数学",
    "name": "ch10_curve_surface_integrals_outline.pdf",
    "path": "grade_1/高等数学/ch10_curve_surface_integrals_outline.pdf",
    "folder": "课程根目录",
    "bytes": 232518,
    "extension": "PDF",
    "kind": "note",
    "subfolder": "课程笔记",
    "downloadPath": "downloads/1-101.pdf"
  },
  {
    "id": "1-81",
    "year": 1,
    "course": "经济学导论",
    "name": "HW5.pdf",
    "path": "grade_1/经济学导论/HW5.pdf",
    "folder": "课程根目录",
    "bytes": 204088,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "作业与报告",
    "downloadPath": "downloads/1-81.pdf"
  },
  {
    "id": "1-82",
    "year": 1,
    "course": "经济学导论",
    "name": "Lect1-经济学概述.pdf",
    "path": "grade_1/经济学导论/Lect1-经济学概述.pdf",
    "folder": "课程根目录",
    "bytes": 5652806,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "课程课件",
    "downloadPath": "downloads/1-82.pdf"
  },
  {
    "id": "1-83",
    "year": 1,
    "course": "经济学导论",
    "name": "Lect10-垄断竞争与寡头.pdf",
    "path": "grade_1/经济学导论/Lect10-垄断竞争与寡头.pdf",
    "folder": "课程根目录",
    "bytes": 2729730,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "课程课件",
    "downloadPath": "downloads/1-83.pdf"
  },
  {
    "id": "1-84",
    "year": 1,
    "course": "经济学导论",
    "name": "Lect11-重要的宏观经济指标.pdf",
    "path": "grade_1/经济学导论/Lect11-重要的宏观经济指标.pdf",
    "folder": "课程根目录",
    "bytes": 4910338,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "课程课件",
    "downloadPath": "downloads/1-84.pdf"
  },
  {
    "id": "1-85",
    "year": 1,
    "course": "经济学导论",
    "name": "Lect12-长期中的货币与物价.pdf",
    "path": "grade_1/经济学导论/Lect12-长期中的货币与物价.pdf",
    "folder": "课程根目录",
    "bytes": 3887004,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "课程课件",
    "downloadPath": "downloads/1-85.pdf"
  },
  {
    "id": "1-86",
    "year": 1,
    "course": "经济学导论",
    "name": "Lect13-短期经济波动.pdf",
    "path": "grade_1/经济学导论/Lect13-短期经济波动.pdf",
    "folder": "课程根目录",
    "bytes": 2177000,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "课程课件",
    "downloadPath": "downloads/1-86.pdf"
  },
  {
    "id": "1-87",
    "year": 1,
    "course": "经济学导论",
    "name": "Lect14-货币政策与财政政策.pdf",
    "path": "grade_1/经济学导论/Lect14-货币政策与财政政策.pdf",
    "folder": "课程根目录",
    "bytes": 1618804,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "课程课件",
    "downloadPath": "downloads/1-87.pdf"
  },
  {
    "id": "1-88",
    "year": 1,
    "course": "经济学导论",
    "name": "Lect15-信息经济学导论.pdf",
    "path": "grade_1/经济学导论/Lect15-信息经济学导论.pdf",
    "folder": "课程根目录",
    "bytes": 1427472,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "课程课件",
    "downloadPath": "downloads/1-88.pdf"
  },
  {
    "id": "1-89",
    "year": 1,
    "course": "经济学导论",
    "name": "Lect2-模型、比较优势与贸易.pdf",
    "path": "grade_1/经济学导论/Lect2-模型、比较优势与贸易.pdf",
    "folder": "课程根目录",
    "bytes": 2137659,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "课程课件",
    "downloadPath": "downloads/1-89.pdf"
  },
  {
    "id": "1-90",
    "year": 1,
    "course": "经济学导论",
    "name": "Lect3-供给与需求.pdf",
    "path": "grade_1/经济学导论/Lect3-供给与需求.pdf",
    "folder": "课程根目录",
    "bytes": 5448943,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "课程课件",
    "downloadPath": "downloads/1-90.pdf"
  },
  {
    "id": "1-91",
    "year": 1,
    "course": "经济学导论",
    "name": "Lect4-政府政策.pdf",
    "path": "grade_1/经济学导论/Lect4-政府政策.pdf",
    "folder": "课程根目录",
    "bytes": 3554305,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "课程课件",
    "downloadPath": "downloads/1-91.pdf"
  },
  {
    "id": "1-92",
    "year": 1,
    "course": "经济学导论",
    "name": "Lect5-福利经济学.pdf",
    "path": "grade_1/经济学导论/Lect5-福利经济学.pdf",
    "folder": "课程根目录",
    "bytes": 2156086,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "课程课件",
    "downloadPath": "downloads/1-92.pdf"
  },
  {
    "id": "1-93",
    "year": 1,
    "course": "经济学导论",
    "name": "Lect6-外部性和公共物品.pdf",
    "path": "grade_1/经济学导论/Lect6-外部性和公共物品.pdf",
    "folder": "课程根目录",
    "bytes": 5304106,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "课程课件",
    "downloadPath": "downloads/1-93.pdf"
  },
  {
    "id": "1-94",
    "year": 1,
    "course": "经济学导论",
    "name": "Lect7-生产成本.pdf",
    "path": "grade_1/经济学导论/Lect7-生产成本.pdf",
    "folder": "课程根目录",
    "bytes": 1292939,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "课程课件",
    "downloadPath": "downloads/1-94.pdf"
  },
  {
    "id": "1-95",
    "year": 1,
    "course": "经济学导论",
    "name": "Lect8-完全竞争 (1).pdf",
    "path": "grade_1/经济学导论/Lect8-完全竞争 (1).pdf",
    "folder": "课程根目录",
    "bytes": 1902713,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "课程课件",
    "downloadPath": "downloads/1-95.pdf"
  },
  {
    "id": "1-96",
    "year": 1,
    "course": "经济学导论",
    "name": "Lect8-完全竞争.pdf",
    "path": "grade_1/经济学导论/Lect8-完全竞争.pdf",
    "folder": "课程根目录",
    "bytes": 1902713,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "课程课件",
    "downloadPath": "downloads/1-96.pdf"
  },
  {
    "id": "1-97",
    "year": 1,
    "course": "经济学导论",
    "name": "Lect9-垄断.pdf",
    "path": "grade_1/经济学导论/Lect9-垄断.pdf",
    "folder": "课程根目录",
    "bytes": 1885837,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "课程课件",
    "downloadPath": "downloads/1-97.pdf"
  },
  {
    "id": "1-16",
    "year": 1,
    "course": "普通物理1",
    "name": "2026第三次作业.docx",
    "path": "grade_1/普通物理1/2026第三次作业.docx",
    "folder": "课程根目录",
    "bytes": 112112,
    "extension": "DOCX",
    "kind": "resource",
    "subfolder": "作业与报告",
    "downloadPath": "downloads/1-16.docx"
  },
  {
    "id": "1-17",
    "year": 1,
    "course": "普通物理1",
    "name": "2026第四次作业.docx",
    "path": "grade_1/普通物理1/2026第四次作业.docx",
    "folder": "课程根目录",
    "bytes": 215360,
    "extension": "DOCX",
    "kind": "resource",
    "subfolder": "作业与报告",
    "downloadPath": "downloads/1-17.docx"
  },
  {
    "id": "1-15",
    "year": 1,
    "course": "普通物理1",
    "name": "2026第一次作业(1).docx",
    "path": "grade_1/普通物理1/2026第一次作业(1).docx",
    "folder": "课程根目录",
    "bytes": 190496,
    "extension": "DOCX",
    "kind": "resource",
    "subfolder": "作业与报告",
    "downloadPath": "downloads/1-15.docx"
  },
  {
    "id": "1-36",
    "year": 1,
    "course": "普通物理1",
    "name": "第二次作业.docx",
    "path": "grade_1/普通物理1/第二次作业.docx",
    "folder": "课程根目录",
    "bytes": 239666,
    "extension": "DOCX",
    "kind": "resource",
    "subfolder": "作业与报告",
    "downloadPath": "downloads/1-36.docx"
  },
  {
    "id": "1-34",
    "year": 1,
    "course": "普通物理1",
    "name": "普物作业1(1).pdf",
    "path": "grade_1/普通物理1/普物作业1(1).pdf",
    "folder": "课程根目录",
    "bytes": 1850486,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "作业与报告",
    "downloadPath": "downloads/1-34.pdf"
  },
  {
    "id": "1-35",
    "year": 1,
    "course": "普通物理1",
    "name": "物理作业2.pdf",
    "path": "grade_1/普通物理1/物理作业2.pdf",
    "folder": "课程根目录",
    "bytes": 1516059,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "作业与报告",
    "downloadPath": "downloads/1-35.pdf"
  },
  {
    "id": "1-18",
    "year": 1,
    "course": "普通物理1",
    "name": "Lect_10_MechanicalWave-1.pdf",
    "path": "grade_1/普通物理1/Lect_10_MechanicalWave-1.pdf",
    "folder": "课程根目录",
    "bytes": 3133579,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "课程课件",
    "downloadPath": "downloads/1-18.pdf"
  },
  {
    "id": "1-19",
    "year": 1,
    "course": "普通物理1",
    "name": "Lect_11_Temperature and Heat.pdf",
    "path": "grade_1/普通物理1/Lect_11_Temperature and Heat.pdf",
    "folder": "课程根目录",
    "bytes": 4094837,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "课程课件",
    "downloadPath": "downloads/1-19.pdf"
  },
  {
    "id": "1-20",
    "year": 1,
    "course": "普通物理1",
    "name": "Lect_12_Thermal Properties.pdf",
    "path": "grade_1/普通物理1/Lect_12_Thermal Properties.pdf",
    "folder": "课程根目录",
    "bytes": 5347498,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "课程课件",
    "downloadPath": "downloads/1-20.pdf"
  },
  {
    "id": "1-21",
    "year": 1,
    "course": "普通物理1",
    "name": "Lect_13_First Thermodynamics Law.pdf",
    "path": "grade_1/普通物理1/Lect_13_First Thermodynamics Law.pdf",
    "folder": "课程根目录",
    "bytes": 1881681,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "课程课件",
    "downloadPath": "downloads/1-21.pdf"
  },
  {
    "id": "1-22",
    "year": 1,
    "course": "普通物理1",
    "name": "Lect_14_Second Thermodynamics Law.pdf",
    "path": "grade_1/普通物理1/Lect_14_Second Thermodynamics Law.pdf",
    "folder": "课程根目录",
    "bytes": 4327073,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "课程课件",
    "downloadPath": "downloads/1-22.pdf"
  },
  {
    "id": "1-23",
    "year": 1,
    "course": "普通物理1",
    "name": "Lect_2_Kinematics.pdf",
    "path": "grade_1/普通物理1/Lect_2_Kinematics.pdf",
    "folder": "课程根目录",
    "bytes": 5405321,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "课程课件",
    "downloadPath": "downloads/1-23.pdf"
  },
  {
    "id": "1-33",
    "year": 1,
    "course": "普通物理1",
    "name": "lect_3_dynamics.pdf",
    "path": "grade_1/普通物理1/lect_3_dynamics.pdf",
    "folder": "课程根目录",
    "bytes": 8422572,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "课程课件",
    "downloadPath": "downloads/1-33.pdf"
  },
  {
    "id": "1-24",
    "year": 1,
    "course": "普通物理1",
    "name": "Lect_4_Work_energy_V2.pdf",
    "path": "grade_1/普通物理1/Lect_4_Work_energy_V2.pdf",
    "folder": "课程根目录",
    "bytes": 8050731,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "课程课件",
    "downloadPath": "downloads/1-24.pdf"
  },
  {
    "id": "1-25",
    "year": 1,
    "course": "普通物理1",
    "name": "Lect_5.2_Momentum-1.pdf",
    "path": "grade_1/普通物理1/Lect_5.2_Momentum-1.pdf",
    "folder": "课程根目录",
    "bytes": 3010663,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "课程课件",
    "downloadPath": "downloads/1-25.pdf"
  },
  {
    "id": "1-26",
    "year": 1,
    "course": "普通物理1",
    "name": "Lect_5.2_Momentum-2.pdf",
    "path": "grade_1/普通物理1/Lect_5.2_Momentum-2.pdf",
    "folder": "课程根目录",
    "bytes": 2962360,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "课程课件",
    "downloadPath": "downloads/1-26.pdf"
  },
  {
    "id": "1-27",
    "year": 1,
    "course": "普通物理1",
    "name": "Lect_6_RigidBody-1 (1).pdf",
    "path": "grade_1/普通物理1/Lect_6_RigidBody-1 (1).pdf",
    "folder": "课程根目录",
    "bytes": 7449938,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "课程课件",
    "downloadPath": "downloads/1-27.pdf"
  },
  {
    "id": "1-28",
    "year": 1,
    "course": "普通物理1",
    "name": "Lect_6_RigidBody-1.pdf",
    "path": "grade_1/普通物理1/Lect_6_RigidBody-1.pdf",
    "folder": "课程根目录",
    "bytes": 7449938,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "课程课件",
    "downloadPath": "downloads/1-28.pdf"
  },
  {
    "id": "1-29",
    "year": 1,
    "course": "普通物理1",
    "name": "Lect_6_RigidBody-2.pdf",
    "path": "grade_1/普通物理1/Lect_6_RigidBody-2.pdf",
    "folder": "课程根目录",
    "bytes": 7672099,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "课程课件",
    "downloadPath": "downloads/1-29.pdf"
  },
  {
    "id": "1-30",
    "year": 1,
    "course": "普通物理1",
    "name": "Lect_7_Equlibrium and elasticity.pdf",
    "path": "grade_1/普通物理1/Lect_7_Equlibrium and elasticity.pdf",
    "folder": "课程根目录",
    "bytes": 3420682,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "课程课件",
    "downloadPath": "downloads/1-30.pdf"
  },
  {
    "id": "1-31",
    "year": 1,
    "course": "普通物理1",
    "name": "Lect_8_Fluids.pdf",
    "path": "grade_1/普通物理1/Lect_8_Fluids.pdf",
    "folder": "课程根目录",
    "bytes": 4720267,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "课程课件",
    "downloadPath": "downloads/1-31.pdf"
  },
  {
    "id": "1-32",
    "year": 1,
    "course": "普通物理1",
    "name": "Lect_9 Oscillation-1.pdf",
    "path": "grade_1/普通物理1/Lect_9 Oscillation-1.pdf",
    "folder": "课程根目录",
    "bytes": 4769400,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "课程课件",
    "downloadPath": "downloads/1-32.pdf"
  },
  {
    "id": "1-80",
    "year": 1,
    "course": "社会实践",
    "name": "广西百色-2025531083-李忱昊.docx",
    "path": "grade_1/社会实践/广西百色-2025531083-李忱昊.docx",
    "folder": "课程根目录",
    "bytes": 52534,
    "extension": "DOCX",
    "kind": "resource",
    "subfolder": "报告与成果",
    "downloadPath": "downloads/1-80.docx"
  },
  {
    "id": "1-79",
    "year": 1,
    "course": "社会实践",
    "name": "finally.pdf",
    "path": "grade_1/社会实践/finally.pdf",
    "folder": "课程根目录",
    "bytes": 225175,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "报告与成果",
    "downloadPath": "downloads/1-79.pdf"
  },
  {
    "id": "1-2",
    "year": 1,
    "course": "中华文明通论",
    "name": "1 导论.pdf",
    "path": "grade_1/中华文明通论/中华文明通论/张璟-哲学/1 导论.pdf",
    "folder": "中华文明通论 / 张璟-哲学",
    "bytes": 16190339,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "课程课件",
    "downloadPath": "downloads/1-2.pdf"
  },
  {
    "id": "1-3",
    "year": 1,
    "course": "中华文明通论",
    "name": "2 殷周之变.pdf",
    "path": "grade_1/中华文明通论/中华文明通论/张璟-哲学/2 殷周之变.pdf",
    "folder": "中华文明通论 / 张璟-哲学",
    "bytes": 6398683,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "课程课件",
    "downloadPath": "downloads/1-3.pdf"
  },
  {
    "id": "1-4",
    "year": 1,
    "course": "中华文明通论",
    "name": "3 先秦诸子.pdf",
    "path": "grade_1/中华文明通论/中华文明通论/张璟-哲学/3 先秦诸子.pdf",
    "folder": "中华文明通论 / 张璟-哲学",
    "bytes": 2525242,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "课程课件",
    "downloadPath": "downloads/1-4.pdf"
  },
  {
    "id": "1-5",
    "year": 1,
    "course": "中华文明通论",
    "name": "4 魏晋+宋明.pdf",
    "path": "grade_1/中华文明通论/中华文明通论/张璟-哲学/4 魏晋+宋明.pdf",
    "folder": "中华文明通论 / 张璟-哲学",
    "bytes": 2178518,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "课程课件",
    "downloadPath": "downloads/1-5.pdf"
  },
  {
    "id": "1-6",
    "year": 1,
    "course": "中华文明通论",
    "name": "5 平时测验题.pdf",
    "path": "grade_1/中华文明通论/中华文明通论/张璟-哲学/5 平时测验题.pdf",
    "folder": "中华文明通论 / 张璟-哲学",
    "bytes": 152017,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "考试与练习",
    "downloadPath": "downloads/1-6.pdf"
  },
  {
    "id": "1-12",
    "year": 1,
    "course": "中华文明通论",
    "name": "计划、市场与大分流.pdf",
    "path": "grade_1/中华文明通论/中华文明通论/方圆-历史/计划、市场与大分流.pdf",
    "folder": "中华文明通论 / 方圆-历史",
    "bytes": 11557455,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "专题课件",
    "downloadPath": "downloads/1-12.pdf"
  },
  {
    "id": "1-10",
    "year": 1,
    "course": "中华文明通论",
    "name": "历史精神.pdf",
    "path": "grade_1/中华文明通论/中华文明通论/方圆-历史/历史精神.pdf",
    "folder": "中华文明通论 / 方圆-历史",
    "bytes": 6950663,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "专题课件",
    "downloadPath": "downloads/1-10.pdf"
  },
  {
    "id": "1-7",
    "year": 1,
    "course": "中华文明通论",
    "name": "中国古代教育变迁.pdf",
    "path": "grade_1/中华文明通论/中华文明通论/方圆-历史/中国古代教育变迁.pdf",
    "folder": "中华文明通论 / 方圆-历史",
    "bytes": 5229771,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "专题课件",
    "downloadPath": "downloads/1-7.pdf"
  },
  {
    "id": "1-9",
    "year": 1,
    "course": "中华文明通论",
    "name": "中国政治文化变迁二.pdf",
    "path": "grade_1/中华文明通论/中华文明通论/方圆-历史/中国政治文化变迁二.pdf",
    "folder": "中华文明通论 / 方圆-历史",
    "bytes": 3807272,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "专题课件",
    "downloadPath": "downloads/1-9.pdf"
  },
  {
    "id": "1-8",
    "year": 1,
    "course": "中华文明通论",
    "name": "中国政治文化变迁一.pdf",
    "path": "grade_1/中华文明通论/中华文明通论/方圆-历史/中国政治文化变迁一.pdf",
    "folder": "中华文明通论 / 方圆-历史",
    "bytes": 6537166,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "专题课件",
    "downloadPath": "downloads/1-8.pdf"
  },
  {
    "id": "1-13",
    "year": 1,
    "course": "中华文明通论",
    "name": "中通-中国古代文学 26春(1).pdf",
    "path": "grade_1/中华文明通论/中华文明通论/白云-文学/中通-中国古代文学 26春(1).pdf",
    "folder": "中华文明通论 / 白云-文学",
    "bytes": 6268054,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "专题课件",
    "downloadPath": "downloads/1-13.pdf"
  },
  {
    "id": "1-14",
    "year": 1,
    "course": "中华文明通论",
    "name": "中通论文 李忱昊 2025531083.docx",
    "path": "grade_1/中华文明通论/中通论文 李忱昊 2025531083.docx",
    "folder": "课程根目录",
    "bytes": 17674,
    "extension": "DOCX",
    "kind": "resource",
    "subfolder": "报告与成果",
    "downloadPath": "downloads/1-14.docx"
  },
  {
    "id": "1-11",
    "year": 1,
    "course": "中华文明通论",
    "name": "宗法、家族.pdf",
    "path": "grade_1/中华文明通论/中华文明通论/方圆-历史/宗法、家族.pdf",
    "folder": "中华文明通论 / 方圆-历史",
    "bytes": 1739554,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "专题课件",
    "downloadPath": "downloads/1-11.pdf"
  },
  {
    "id": "1-1",
    "year": 1,
    "course": "中华文明通论",
    "name": "cheatsheet(1).docx",
    "path": "grade_1/中华文明通论/中华文明通论/cheatsheet(1).docx",
    "folder": "中华文明通论",
    "bytes": 18770,
    "extension": "DOCX",
    "kind": "note",
    "subfolder": "复习与总结",
    "downloadPath": "downloads/1-1.docx"
  },
  {
    "id": "2-130",
    "year": 2,
    "course": "大学化学",
    "name": "Chemistry Student Solutions Manual, 10th ed. by Raymond Chang (Raymond Chang) (z-library.sk, 1lib.sk, z-lib.sk).pdf",
    "path": "grade_2/s1/大学化学/Chemistry Student Solutions Manual, 10th ed. by Raymond Chang (Raymond Chang) (z-library.sk, 1lib.sk, z-lib.sk).pdf",
    "folder": "课程根目录",
    "bytes": 10009156,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "教材与参考书",
    "downloadPath": null
  },
  {
    "id": "2-151",
    "year": 2,
    "course": "概率论",
    "name": "概率导论 第2版 (Dimitri P. Bertsekas John N. Tsitsiklis) (z-library.sk, 1lib.sk, z-lib.sk).pdf",
    "path": "grade_2/s1/概率论/概率导论 第2版 (Dimitri P. Bertsekas John N. Tsitsiklis) (z-library.sk, 1lib.sk, z-lib.sk).pdf",
    "folder": "课程根目录",
    "bytes": 18673991,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "教材与参考书",
    "downloadPath": null
  },
  {
    "id": "2-153",
    "year": 2,
    "course": "概率论",
    "name": "概率论导论 .pdf",
    "path": "grade_2/s1/概率论/概率论导论 .pdf",
    "folder": "课程根目录",
    "bytes": 162462786,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "教材与参考书",
    "downloadPath": null
  },
  {
    "id": "2-152",
    "year": 2,
    "course": "概率论",
    "name": "概率论导论 ( etc.) (z-library.sk, 1lib.sk, z-lib.sk).pdf",
    "path": "grade_2/s1/概率论/概率论导论 ( etc.) (z-library.sk, 1lib.sk, z-lib.sk).pdf",
    "folder": "课程根目录",
    "bytes": 162462786,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "教材与参考书",
    "downloadPath": null
  },
  {
    "id": "2-149",
    "year": 2,
    "course": "概率论",
    "name": "bertsekas_tsitsiklis_probability.pdf",
    "path": "grade_2/s1/概率论/bertsekas_tsitsiklis_probability.pdf",
    "folder": "课程根目录",
    "bytes": 1743247,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "教材与参考书",
    "downloadPath": null
  },
  {
    "id": "2-139",
    "year": 2,
    "course": "概率论",
    "name": "HW_PIC_1.png",
    "path": "grade_2/s1/概率论/Homework/HW1/HW_PIC_1.png",
    "folder": "Homework / HW1",
    "bytes": 880216,
    "extension": "PNG",
    "kind": "resource",
    "subfolder": "作业与报告",
    "downloadPath": "downloads/2-139.png"
  },
  {
    "id": "2-140",
    "year": 2,
    "course": "概率论",
    "name": "HW_PIC_2.png",
    "path": "grade_2/s1/概率论/Homework/HW1/HW_PIC_2.png",
    "folder": "Homework / HW1",
    "bytes": 720892,
    "extension": "PNG",
    "kind": "resource",
    "subfolder": "作业与报告",
    "downloadPath": "downloads/2-140.png"
  },
  {
    "id": "2-138",
    "year": 2,
    "course": "概率论",
    "name": "HW1_program.py",
    "path": "grade_2/s1/概率论/Homework/HW1/HW1_program.py",
    "folder": "Homework / HW1",
    "bytes": 480,
    "extension": "PY",
    "kind": "resource",
    "subfolder": "作业与报告",
    "downloadPath": "downloads/2-138.py"
  },
  {
    "id": "2-137",
    "year": 2,
    "course": "概率论",
    "name": "HW1.pdf",
    "path": "grade_2/s1/概率论/Homework/HW1/HW1.pdf",
    "folder": "Homework / HW1",
    "bytes": 192729,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "作业与报告",
    "downloadPath": "downloads/2-137.pdf"
  },
  {
    "id": "2-144",
    "year": 2,
    "course": "概率论",
    "name": "import numpy as np.py",
    "path": "grade_2/s1/概率论/Homework/HW1/import numpy as np.py",
    "folder": "Homework / HW1",
    "bytes": 723,
    "extension": "PY",
    "kind": "resource",
    "subfolder": "作业与报告",
    "downloadPath": "downloads/2-144.py"
  },
  {
    "id": "2-150",
    "year": 2,
    "course": "概率论",
    "name": "introduction-to-probability-by-joseph-k-blitzstein-and-jessica-hwang.pdf",
    "path": "grade_2/s1/概率论/introduction-to-probability-by-joseph-k-blitzstein-and-jessica-hwang.pdf",
    "folder": "课程根目录",
    "bytes": 13448695,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "教材与参考书",
    "downloadPath": null
  },
  {
    "id": "2-148",
    "year": 2,
    "course": "概率论",
    "name": "L1(1).pdf",
    "path": "grade_2/s1/概率论/L1(1).pdf",
    "folder": "课程根目录",
    "bytes": 8789399,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "课程课件",
    "downloadPath": "downloads/2-148.pdf"
  },
  {
    "id": "2-141",
    "year": 2,
    "course": "概率论",
    "name": "SI_140A_01_Homework_1.pdf",
    "path": "grade_2/s1/概率论/Homework/HW1/SI_140A_01_Homework_1.pdf",
    "folder": "Homework / HW1",
    "bytes": 169735,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "作业与报告",
    "downloadPath": "downloads/2-141.pdf"
  },
  {
    "id": "2-142",
    "year": 2,
    "course": "概率论",
    "name": "SI_140A_01_Homework_1.tex",
    "path": "grade_2/s1/概率论/Homework/HW1/SI_140A_01_Homework_1.tex",
    "folder": "Homework / HW1",
    "bytes": 17845,
    "extension": "TEX",
    "kind": "resource",
    "subfolder": "作业与报告",
    "downloadPath": "downloads/2-142.tex"
  },
  {
    "id": "2-145",
    "year": 2,
    "course": "概率论",
    "name": "SI_140A_01_Homework_2 (1).pdf",
    "path": "grade_2/s1/概率论/Homework/HW2/SI_140A_01_Homework_2 (1).pdf",
    "folder": "Homework / HW2",
    "bytes": 130398,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "作业与报告",
    "downloadPath": "downloads/2-145.pdf"
  },
  {
    "id": "2-146",
    "year": 2,
    "course": "概率论",
    "name": "SI_140A_01_Homework_2 (1).tex",
    "path": "grade_2/s1/概率论/Homework/HW2/SI_140A_01_Homework_2 (1).tex",
    "folder": "Homework / HW2",
    "bytes": 18597,
    "extension": "TEX",
    "kind": "resource",
    "subfolder": "作业与报告",
    "downloadPath": "downloads/2-146.tex"
  },
  {
    "id": "2-147",
    "year": 2,
    "course": "概率论",
    "name": "SI_140A_01_Homework_2.tex",
    "path": "grade_2/s1/概率论/Homework/HW2/SI_140A_01_Homework_2.tex",
    "folder": "Homework / HW2",
    "bytes": 14610,
    "extension": "TEX",
    "kind": "resource",
    "subfolder": "作业与报告",
    "downloadPath": "downloads/2-147.tex"
  },
  {
    "id": "2-143",
    "year": 2,
    "course": "概率论",
    "name": "SI_140A_01_Program_1(1).pdf",
    "path": "grade_2/s1/概率论/Homework/HW1/SI_140A_01_Program_1(1).pdf",
    "folder": "Homework / HW1",
    "bytes": 89304,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "作业与报告",
    "downloadPath": "downloads/2-143.pdf"
  },
  {
    "id": "2-162",
    "year": 2,
    "course": "模拟电路",
    "name": "课程资料网址.textClipping",
    "path": "grade_2/s1/模拟电路/课程资料网址.textClipping",
    "folder": "课程根目录",
    "bytes": 160,
    "extension": "TEXTCLIPPING",
    "kind": "resource",
    "subfolder": "课程说明与链接",
    "downloadPath": "downloads/2-162.textclipping"
  },
  {
    "id": "2-159",
    "year": 2,
    "course": "模拟电路",
    "name": "模拟电子技术基础 第四版 (童诗白, 华成英, 清华大学电子学教研组).pdf",
    "path": "grade_2/s1/模拟电路/模拟电子技术基础 第四版 (童诗白, 华成英, 清华大学电子学教研组).pdf",
    "folder": "课程根目录",
    "bytes": 25129017,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "教材与参考书",
    "downloadPath": null
  },
  {
    "id": "2-157",
    "year": 2,
    "course": "模拟电路",
    "name": "微电子电路 第5版（上册） (Adel S. Sedra, Kenneth C. Smith etc.) (z-library.sk, 1lib.sk, z-lib.sk).pdf",
    "path": "grade_2/s1/模拟电路/微电子电路 第5版（上册） (Adel S. Sedra, Kenneth C. Smith etc.) (z-library.sk, 1lib.sk, z-lib.sk).pdf",
    "folder": "课程根目录",
    "bytes": 107809054,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "教材与参考书",
    "downloadPath": null
  },
  {
    "id": "2-158",
    "year": 2,
    "course": "模拟电路",
    "name": "微电子电路 第5版（下册） (Adel S. Sedra, Kenneth C. Smith etc.) (z-library.sk, 1lib.sk, z-lib.sk).pdf",
    "path": "grade_2/s1/模拟电路/微电子电路 第5版（下册） (Adel S. Sedra, Kenneth C. Smith etc.) (z-library.sk, 1lib.sk, z-lib.sk).pdf",
    "folder": "课程根目录",
    "bytes": 39474804,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "教材与参考书",
    "downloadPath": null
  },
  {
    "id": "2-154",
    "year": 2,
    "course": "模拟电路",
    "name": "HW1 .pdf",
    "path": "grade_2/s1/模拟电路/Homework/HW1 .pdf",
    "folder": "Homework",
    "bytes": 2870669,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "作业与报告",
    "downloadPath": "downloads/2-154.pdf"
  },
  {
    "id": "2-160",
    "year": 2,
    "course": "模拟电路",
    "name": "Lecture2.pdf",
    "path": "grade_2/s1/模拟电路/课件/Lecture2.pdf",
    "folder": "课件",
    "bytes": 2877290,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "课程课件",
    "downloadPath": "downloads/2-160.pdf"
  },
  {
    "id": "2-155",
    "year": 2,
    "course": "模拟电路",
    "name": "Lecture3_知识点整理.pdf",
    "path": "grade_2/s1/模拟电路/output/pdf/Lecture3_知识点整理.pdf",
    "folder": "output / pdf",
    "bytes": 209541,
    "extension": "PDF",
    "kind": "note",
    "subfolder": "课程笔记",
    "downloadPath": "downloads/2-155.pdf"
  },
  {
    "id": "2-156",
    "year": 2,
    "course": "模拟电路",
    "name": "Lecture3_知识点整理.tex",
    "path": "grade_2/s1/模拟电路/output/pdf/Lecture3_知识点整理.tex",
    "folder": "output / pdf",
    "bytes": 15763,
    "extension": "TEX",
    "kind": "note",
    "subfolder": "课程笔记",
    "downloadPath": "downloads/2-156.tex"
  },
  {
    "id": "2-161",
    "year": 2,
    "course": "模拟电路",
    "name": "Lecture3.pdf",
    "path": "grade_2/s1/模拟电路/课件/Lecture3.pdf",
    "folder": "课件",
    "bytes": 2363031,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "课程课件",
    "downloadPath": "downloads/2-161.pdf"
  },
  {
    "id": "2-131",
    "year": 2,
    "course": "数字电路",
    "name": "数电HW1.pdf",
    "path": "grade_2/s1/数字电路/作业/数电HW1.pdf",
    "folder": "作业",
    "bytes": 994675,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "作业与报告",
    "downloadPath": "downloads/2-131.pdf"
  },
  {
    "id": "2-132",
    "year": 2,
    "course": "数字电路",
    "name": "数字电子技术基础 (阎石主编) .pdf",
    "path": "grade_2/s1/数字电路/数字电子技术基础 (阎石主编) .pdf",
    "folder": "课程根目录",
    "bytes": 69914879,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "教材与参考书",
    "downloadPath": null
  },
  {
    "id": "2-134",
    "year": 2,
    "course": "数字电路",
    "name": "lecture_1_p1.pdf",
    "path": "grade_2/s1/数字电路/课件/lecture_1_p1.pdf",
    "folder": "课件",
    "bytes": 1987567,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "课程课件",
    "downloadPath": "downloads/2-134.pdf"
  },
  {
    "id": "2-135",
    "year": 2,
    "course": "数字电路",
    "name": "lecture_1_p2.pdf",
    "path": "grade_2/s1/数字电路/课件/lecture_1_p2.pdf",
    "folder": "课件",
    "bytes": 1979308,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "课程课件",
    "downloadPath": "downloads/2-135.pdf"
  },
  {
    "id": "2-136",
    "year": 2,
    "course": "数字电路",
    "name": "lecture_1_p3.pdf",
    "path": "grade_2/s1/数字电路/课件/lecture_1_p3.pdf",
    "folder": "课件",
    "bytes": 1397526,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "课程课件",
    "downloadPath": "downloads/2-136.pdf"
  },
  {
    "id": "2-133",
    "year": 2,
    "course": "数字电路",
    "name": "Syllabus 2026 Fall.pdf",
    "path": "grade_2/s1/数字电路/课件/Syllabus 2026 Fall.pdf",
    "folder": "课件",
    "bytes": 600019,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "课程说明与链接",
    "downloadPath": "downloads/2-133.pdf"
  },
  {
    "id": "2-125",
    "year": 2,
    "course": "cs100",
    "name": "1.c",
    "path": "grade_2/s1/cs100/program/class_program/1.c",
    "folder": "program / class_program",
    "bytes": 122,
    "extension": "C",
    "kind": "resource",
    "subfolder": "代码与附件",
    "downloadPath": "downloads/2-125.c"
  },
  {
    "id": "2-126",
    "year": 2,
    "course": "cs100",
    "name": "2.c",
    "path": "grade_2/s1/cs100/program/class_program/2.c",
    "folder": "program / class_program",
    "bytes": 119,
    "extension": "C",
    "kind": "resource",
    "subfolder": "代码与附件",
    "downloadPath": "downloads/2-126.c"
  },
  {
    "id": "2-117",
    "year": 2,
    "course": "cs100",
    "name": "C Primer Plus 第6版 中文版 ([美]史蒂芬·普拉达(Stephen Prata)) (z-library.sk, 1lib.sk, z-lib.sk).pdf",
    "path": "grade_2/s1/cs100/C Primer Plus 第6版 中文版 ([美]史蒂芬·普拉达(Stephen Prata)) (z-library.sk, 1lib.sk, z-lib.sk).pdf",
    "folder": "课程根目录",
    "bytes": 22725649,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "教材与参考书",
    "downloadPath": null
  },
  {
    "id": "2-118",
    "year": 2,
    "course": "cs100",
    "name": "C++ Primer Plus 中文版（第6版）（2019重印） (Stephen Prata, 张海龙, 袁国忠) (z-library.sk, 1lib.sk, z-lib.sk).pdf",
    "path": "grade_2/s1/cs100/C++ Primer Plus 中文版（第6版）（2019重印） (Stephen Prata, 张海龙, 袁国忠) (z-library.sk, 1lib.sk, z-lib.sk).pdf",
    "folder": "课程根目录",
    "bytes": 42137682,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "教材与参考书",
    "downloadPath": null
  },
  {
    "id": "2-127",
    "year": 2,
    "course": "cs100",
    "name": "ex.c",
    "path": "grade_2/s1/cs100/program/ex.c",
    "folder": "program",
    "bytes": 460,
    "extension": "C",
    "kind": "resource",
    "subfolder": "代码与附件",
    "downloadPath": "downloads/2-127.c"
  },
  {
    "id": "2-124",
    "year": 2,
    "course": "cs100",
    "name": "HW1_student_starter.zip",
    "path": "grade_2/s1/cs100/program/HW/HW1_student_starter.zip",
    "folder": "program / HW",
    "bytes": 15585,
    "extension": "ZIP",
    "kind": "resource",
    "subfolder": "作业与报告",
    "downloadPath": "downloads/2-124.zip"
  },
  {
    "id": "2-128",
    "year": 2,
    "course": "cs100",
    "name": "lec01.pdf",
    "path": "grade_2/s1/cs100/课件/lec01.pdf",
    "folder": "课件",
    "bytes": 5708884,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "课程课件",
    "downloadPath": "downloads/2-128.pdf"
  },
  {
    "id": "2-129",
    "year": 2,
    "course": "cs100",
    "name": "lec02.pdf",
    "path": "grade_2/s1/cs100/课件/lec02.pdf",
    "folder": "课件",
    "bytes": 9540981,
    "extension": "PDF",
    "kind": "resource",
    "subfolder": "课程课件",
    "downloadPath": "downloads/2-129.pdf"
  },
  {
    "id": "2-120",
    "year": 2,
    "course": "cs100",
    "name": "p2.c",
    "path": "grade_2/s1/cs100/program/HW/HW1_student_starter/p2.c",
    "folder": "program / HW / HW1_student_starter",
    "bytes": 862,
    "extension": "C",
    "kind": "resource",
    "subfolder": "作业与报告",
    "downloadPath": "downloads/2-120.c"
  },
  {
    "id": "2-121",
    "year": 2,
    "course": "cs100",
    "name": "p3.c",
    "path": "grade_2/s1/cs100/program/HW/HW1_student_starter/p3.c",
    "folder": "program / HW / HW1_student_starter",
    "bytes": 646,
    "extension": "C",
    "kind": "resource",
    "subfolder": "作业与报告",
    "downloadPath": "downloads/2-121.c"
  },
  {
    "id": "2-122",
    "year": 2,
    "course": "cs100",
    "name": "p4.c",
    "path": "grade_2/s1/cs100/program/HW/HW1_student_starter/p4.c",
    "folder": "program / HW / HW1_student_starter",
    "bytes": 1051,
    "extension": "C",
    "kind": "resource",
    "subfolder": "作业与报告",
    "downloadPath": "downloads/2-122.c"
  },
  {
    "id": "2-123",
    "year": 2,
    "course": "cs100",
    "name": "p5.c",
    "path": "grade_2/s1/cs100/program/HW/HW1_student_starter/p5.c",
    "folder": "program / HW / HW1_student_starter",
    "bytes": 865,
    "extension": "C",
    "kind": "resource",
    "subfolder": "作业与报告",
    "downloadPath": "downloads/2-123.c"
  },
  {
    "id": "2-119",
    "year": 2,
    "course": "cs100",
    "name": "README.md",
    "path": "grade_2/s1/cs100/program/HW/HW1_student_starter/README.md",
    "folder": "program / HW / HW1_student_starter",
    "bytes": 3345,
    "extension": "MD",
    "kind": "resource",
    "subfolder": "作业与报告",
    "downloadPath": "downloads/2-119.md"
  }
];
